### PR TITLE
chore(babel): use `babel-preset-env`

### LINKED ISSUE #195: `babel-preset-latest` is deprecated
- `polished` version: v1.1.3

polished still uses `babel-preset-latest` which is deprecated. Babel suggests to migrate to `babel-preset-env`.
screen shot 2017-06-18 at 00 05 44
https://babeljs.io/docs/plugins/preset-latest/

### PR DESCRIPTION
**Pull request by luftywiranda13**
`babel-preset-latest` is deprecated
https://babeljs.io/docs/plugins/preset-latest/

close #195

### CODE REVIEW

**Comment by luftywiranda13** [comment]
failed on script `build:docs:site` && `build:docs:readme`.
they're not related to what I changed by this PR

**Comment by bhough** [comment]
@luftywiranda13 #198 will address the build issues with this PR. Also, looks like some unrelated additions in the flow-typed folder?

**Comment by luftywiranda13** [comment]
@bhough I ran `flow-typed update` to get any libdefs from this project's dependencies provided by [flow-typed](https://github.com/flowtype/flow-typed).
I did that because I saw many missing `libdefs` in the `./flow-typed/` folder. maybe we need those libdefs in the future

**Comment by bhough** [comment]
Closing in favor of #203. The documentation.js issue did a number on this PR and I can't get the docs to build correctly. Faster to just do a clean PR with the changes.

**Pull request closed without merging**
