### PR TITLE
[WIP] Calculating with unit-suffixed values

### PR DESCRIPTION
**Pull request by tobilen**
adresses https://github.com/styled-components/polished/issues/270

* Adds a `calc` helper
calc provides an idx-like syntax to perform arithmetics on unit-suffixed css values.
Example:
```js
import { calc, stripUnit } from 'polished';

const  base = '12px';
const double = calc(base, baseAsNumber => baseAsNumber * 2); // returns '24px'

const one = '1px';
const plusOne = calc(base, baseAsNumber => baseAsNumber + stripUnit(one)); // returns '13px'
```
* Adds a `extractUnit` helper
counterpart to `stripUnit`, `extractUnit` takes in a unit-suffixed css value and returns the unit type as string. Empty string if no type could be extracted
Example:
```js
import { extractUnit } from 'polished';

const unit = extractUnit('12px') // returns 'px'
```

### CODE REVIEW

**Comment by bhough** [comment]
Thanks for putting this together @tobilen. I will spend some time looking at this over the weekend. One thing I will throw out there initially is we probably don't want to use `calc` as the module name given that CSS also has it and it could possibly be confusing.

**Comment by tobilen** [comment]
hey there,

i thought about this potential problem as well. since this PR was opened, we've implemented the functionality in our internal tool lib, and - speaking from 2 weeks of usage experience - there isn't much chance of confusing the two. happy to change it if you come up with something better though!

**Comment by tobilen** [comment]
@nikgraf @bhough @mxstbr whats the status on this PR?

**Comment by bhough** [comment]
@tobilen sorry, I've been swamped and haven't gotten to much polished stuff the past few weeks. I have some time set aside this week to go over PRs and Issues and I will take a deeper look at this.

**Comment by tobilen** [comment]
apparently not happening

**Comment by goodmind** [comment]
why this was closed?

**Comment by tobilen** [comment]
@goodmind because the maintainers didn't seem interested in it

**Pull request closed without merging**
