### PR TITLE
feat(color): toColorString Performance Improvements

### PR DESCRIPTION
**Pull request by sandiiarov**
Split toColorString into hslToColorString & rgbToColorString
Addresses: #176

### CODE REVIEW

**Comment by bhough** [comment]
Thanks for the PR @Alex4S. This is a bit item on our v2 list! I've requested a review from @nikgraf since he did a lot of the work on the color side. One note is, while all internal implementation should be moved over to the new specific methods, we should leave `toColorString` in for now and mark it as deprecated. We are working on introducing new code that will warn the user of this (among many other things).

**Comment by nikgraf** [comment]
The PR itself looks good. My original intention was to keep `toColorString` for people doing more complex custom color manipulation. It's quite useful when dealing with color objects.

If we want to deprecate it then the PR is fine. If now we either copy the code to have it in both or refactor to reuse the `rgbToColorString` and `hslToColorString` in `toColorString`.

@bhough thoughts?

**Comment by bhough** [comment]
@sandiiarov if we could get the conflicts resolved on this, we'd like to get this reviewed/merged ASAP. Let me know if you think you won't have time.

**Comment by bhough** [comment]
Conflicts resolved and pulled into #398.

**Pull request closed without merging**
