### PR TITLE
feat(fontFace): Add missing font-face properties to mixin

### LINKED ISSUE #286: font-display in the fontFace helper
First of all thanks for the great library; it's saved us loads of time.

Would anyone object to including [`font-display`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) in the `fontFace` helper?

We want to start using it as a progressive enhancement, so happy to put together a PR for this?

While I'm at it would it be worth adding `font-variation-settings` and `font-feature-settings` too? They're the only other `@font-face` rules missing.

### PR DESCRIPTION
**Pull request by oliverjam**
Add font-display, font-feature-settings & font-variation-settings to fontDisplay mixin

closes #286

### CODE REVIEW

**Comment by bhough** [comment]
Thanks @oliverjam! I am out of the country for a couple weeks, but will give this a look when I get back if one of the guys doesn't get to it before then.

**Comment by oliverjam** [comment]
Thanks, no rush :)

I'm not sure why the CI is failing—the TypeScript test passes on my machine and the interfaces seem to be generated correctly :/

**Comment by bhough** [comment]
@oliverjam The issue is that the typescript test itself needs updated: https://github.com/styled-components/polished/blob/master/typescript-test.ts#L12

However, we are temporarily removing TS support in 2.0. I'm aiming to get a base 2.0 branch out by the weekend that has the updated build for 2.0, then we can do this PR off that branch.

**Comment by bhough** [comment]
@oliverjam you will need to rebase this onto `version-2` and probably update your snapshots do to some changes with quotes in snapshots in the latest version of Jest.

**Comment by oliverjam** [comment]
@bhough Oops, don't know how I missed that, sorry. I'll do the rebase—should I update the TypeScript test anyway or is that going to get totally changed when you re-add TS support?

**Comment by bhough** [comment]
Closing this in favor of #299 since Travis is refusing to pick up the new build config for this PR for some reason.

**Pull request closed without merging**
