### PR TITLE
feat(color): Add contrastRatio mixin

### PR DESCRIPTION
**Pull request by Raicuparta**
Addresses #302

### CODE REVIEW

**Comment by bhough** [comment]
Thanks for submitting this @Raicuparta. First question I have is how would you see this being used in production? I'm just wondering if we are introducing a module that is great during development but doesn't see production use and if there is a way to possibly add to the api of one of the related modules (like getLuminance) for this purpose.

**Comment by Raicuparta** [comment]
@bhough Making a tool that lets the user pick foreground / background colors. This shortcut would  be useful for warning users if they're picking two colors with not enough contrast between them.

Maybe @brianespinosa can chime in since he also has a need for it?

**Comment by brianespinosa** [comment]
@bhough @Raicuparta Good morning!

Our use case here is theming. I work on an enterprise product that allows a user to provide a brand color that will change that color throughout our product. In the case of buttons, we sometimes need to know if we should use white or black text on top of the button for legibility.

Because that brand color could be anything, we actually need that check to happen in production, not development.

For more clarity, in case it's useful information, we are using Fela for creating all of our styles.

**Comment by bhough** [comment]
Thanks for the use cases! @brianespinosa It sounds like https://polished.js.org/docs/#readablecolor would solve that issue unless I'm not fully understanding the use case.

**Comment by Raicuparta** [comment]
From #302:
> Basically this would be similar to readableColor() except you are not limited to only returning black/white based on the single color passed.

This particular case could be solved by having some way of telling readableColor() to return something other than pure black / white, like some optional parameter.

And now that I think about it, I suppose my use case example maybe falls outside the scope of polished, since warning users about contrast problems isn't really style-related.

**Comment by bhough** [comment]
@Raicuparta Maybe there is something in a PR that modifies `readableColor` to allow the user to pass colors to override the black and white it currently returns.

**Comment by brianespinosa** [comment]
Yes, this would work... and probably makes more sense as an optional parameter than adding a new function that does almost the same thing:  >@Raicuparta Maybe there is something in a PR that modifies readableColor to allow the user to pass colors to override the black and white it currently returns.

**Comment by brianespinosa** [comment]
[Here are some examples from TinyColor that are doing similar things](https://github.com/bgrins/TinyColor#readability). I don't think we necessarily need all of these, but this one use case proposed in #302 would be enough to accomplish all of the Readability type functions referenced in TinyColor.

**Comment by bhough** [comment]
@Raicuparta I still think we can make it work, but might need to mess with the typing for the curry module. We are doing something similar with with `mix` to address #244. I haven't dug too deep into it yet though.

**Comment by brianespinosa** [comment]
@bhough Good morning! I am just trying to follow along here. Is this something being resolved elsewhere, or are you just simply closing the old PR out and leaving #302 open to capture the feature req?

**Comment by bhough** [comment]
@brianespinosa Yes, the approach that this takes is ultimately not the way we want to go, and some work needs to be done on the Flow side to allow us to modify readableColor. So when we tackle this is it will be done as a new PR.

**Pull request closed without merging**
