### PR TITLE
Add ellipsis mixin

### PR DESCRIPTION
**Pull request by bhough**
Added ellipsis mixin and associated tests. Also added coverage to .gitignore and dependencies for handling spreads in babel.

https://github.com/styled-components/polished/issues/1

### CODE REVIEW

**Comment by bhough** [comment]
@mxstbr ready for review

**Comment by mxstbr** [comment]
I think if we merge this, `semantic-release` is going to publish a bunch of new versions. Do we want that yet? I did `chore()` over at #16 so we don't release anything yet to npm...

**Comment by bhough** [comment]
ah forgot we had that turned on. I will amend these into chores.

**Comment by bhough** [comment]
@mxstbr this is ready to go sir

**Comment by mxstbr** [comment]
What, why does this have conflicts now?

**Comment by bhough** [comment]
@mxstbr it looks like it was an ordering issue. Think we should've merged #17 then #18. Either way it was just a whitespace issue. Should be good to merge now.

**Pull request merged**
