### PR TITLE
Add hideText Mixin

### PR DESCRIPTION
**Pull request by bhough**
Addresses line item in #1

### CODE REVIEW

**Comment by mxstbr** [comment]
Oh my god this has conflicts now too! Ugh.

**Comment by bhough** [comment]
rebased and good to go.

**Comment by bhough** [comment]
@mxstbr I actually don't have merge privileges ☹️

**Comment by mxstbr** [comment]
You should have merge privileges though?

**Comment by bhough** [comment]
Unfortunately not, the button is greyed out for me and says I don't have write permissions for the repo.

**Pull request merged**
