### PR TITLE
feat(mixins): Add hideVisually mixin

### PR DESCRIPTION
**Pull request by rawrmonstar**
Add mixin to visually hide content but leave it accessible to screen readers.

### CODE REVIEW

**Comment by bhough** [comment]
Hey @rawrmonstar, thanks for this PR! This is definitely something worth including. I will give this a review this week and get you a couple additional steps that are needed when we add a module.

**Comment by rawrmonstar** [comment]
@bhough when I run `npm run build` all the links in docs/docs/index.html are changed to link to my forked repo. Am I doing something wrong?

**Comment by bhough** [comment]
@rawrmonstar ahhh, no you're not. That is an issue I forgot about. I will pull it down tonight and run the build on my machine and push it up to your branch and see if there are any remaining issues.

**Comment by bhough** [comment]
Closed in favor of #272

**Pull request closed without merging**
