### PR TITLE
perf(modules): Change module build to better facilitate individual imports

### PR DESCRIPTION
**Pull request by bhough**
Addresses comments: #178 

This will support `import <module> from 'polished/utils/<module>'`.

This is non-breaking so folks using `import <module> from 'polished/lib/<type>/<module>'`. However, I would like to remove this support in V2 as that was never the official recommendation.

Of course normal destructured imports will continue to work as before.

### CODE REVIEW

**Comment by bhough** [comment]
@kof @nikgraf @mxstbr So this is the simplest approach to get us to what was described in #178. It basically moves the build individual modules out of `/lib` to the root of the package. Thoughts?

**Comment by bhough** [comment]
@mxstbr I thought about that or even just putting them all flat in the root. It's not a pretty solution organizationally, but easier to import.

Thoughts?

**Comment by nikgraf** [comment]
@bhough that's a pity, I was hoping we could avoid direct imports …

**Comment by bhough** [comment]
@nikgraf were you hoping we could avoid them due to tree shaking handling that for us?

**Comment by mxstbr** [comment]
Putting that all flat in the root is super duper annoying for development as you'll have dozens of files just sitting there cluttering your editor, next to having to remember to add all new utils to the `.gitignore` etc.

I'd much prefer just having them in a folder. Maybe `/u/` to be short?

**Pull request closed without merging**
