### PR TITLE
perf(tooling): Use loose mode for the babel transpilation

### PR DESCRIPTION
**Pull request by Andarist**
See https://github.com/styled-components/polished/issues/262#issuecomment-339904411

### CODE REVIEW

**Comment by Andarist** [comment]
Ofc it potentially can introduce some issues, its after all a loose mode and is not that strict about following the spec **exactly**, but it provides the same functionality. Spec must assume many different scenarios, which most of them happen only rarely in the code in the wild.

And imho if your code need those speced behaviours it is poorly/bizarrely written and should be changed or it is too clever and should be changed too 😉

Personally I'm using `loose` mode exclusively in all libraries that I maintain (4~) and in all of my apps - never had any issues with it, not myself and not reported by anyone.

**Comment by Andarist** [comment]
ping @bhough , any further thoughts on this?

**Comment by bhough** [comment]
@Andarist I think for a short term fix, I'm willing to go this route. Ideally, I would like to see the plugin move to one of the solutions you suggested (https://github.com/styled-components/polished/issues/262#issuecomment-339904411) as soon as possible. Is there anything I can do to help with that?

**Comment by Andarist** [comment]
@bhough While ofc this fix has fixed only symptoms, I feel like it should stay permanently, most OSS projects use `loose` mode without any troubles - i.e. [react](https://github.com/facebook/react/blob/master/.babelrc), [redux](https://github.com/reactjs/redux/blob/master/.babelrc) and others.

> Ideally, I would like to see the plugin move to one of the solutions you suggested (#262 (comment)) as soon as possible. Is there anything I can do to help with that?

Thanks for the kind offer! I've already sent "defineProperty calls folding" PRs to babel, but they didn't yet get thorough reviews. If we could think about how `annotate-pure-calls` plugin could be resistant against such cases, that would be cool.

**Pull request merged**
