### PR TITLE
feat(rgba): Fade color with rgba module

### PR DESCRIPTION
**Pull request by bhough**
rgba now can accept a hex or named CSS color value and an alpha value to fade a color.

Addresses request made in #104

### CODE REVIEW

**Comment by nikgraf** [comment]
Still not a fan, `transparentize(0.3, '#fff')` is a much more descriptive API :)

Nevertheless the PR looks good. One open question: Should we allow strings then rgb as well? If not that seems to be pretty inconsistent.

**Comment by bhough** [comment]
@nikgraf I've been kinda torn on this one myself. There are a couple things at play here.

1) it seems like the consensus is that users don't seem to want to do the math and would rather have the alpha value just be a pass in for the alpha level as opposed to the amount you want to transparentize by.

2) because the goal of the project is still to replace sass/less and their libraries, users seem to want rgba to work the same way.

Which still leaves us with the question of, is there a solution that accomplishes these things without making us feel bad about including it in the library?

Can you give me an example of what you mean when you say :

> Should we allow strings then rgb as well?

**Comment by nikgraf** [comment]
Hmm, I can't remember what I meant by strings, but the PR looks good to me.

If we haven't found a better solution after that time I think the best course of action is to merge it :)

**Comment by bhough** [comment]
This is not a breaking change, so I'm fine with merging it.

**Pull request merged**
