### PR TITLE
Error/Warning Handling

### PR DESCRIPTION
**Pull request by bhough**
Handler for pretty printed warnings and errors in console in development mode.

### CODE REVIEW

**Comment by bhough** [comment]
@mxstbr @nikgraf rough WIP PR. Looking for comments on implementation and the api. Feels a bit verbose (though less so than my last attempt).

**Comment by mxstbr** [comment]
Screenshot:

screen shot 2017-03-26 at 20 18 56

I like it!

**Comment by nikgraf** [comment]
I like it too @bhough - let's do it 👍

**Comment by bhough** [comment]
Great, I'll get this initial PR cleaned up and passing CI so we can merge it, and I'll start working my way through converting errors over in a separate PR.

**Comment by mxstbr** [comment]
Can we make sure errors are stripped out in prod?

**Comment by bhough** [comment]
@mxstbr @nikgraf this is good to go. Confirmed that errors will be stripped in production if wrapper properly. Will open a new branch to start implementing first on existing errors, then a second one that start getting more error coverage.

**Comment by bhough** [comment]
@mxstbr @nikgraf just bumping this so we can get it merged. Currently working on a separate branch to handle wrapping existing messages that depends on this.

**Comment by bhough** [comment]
Closing in favor of #136

**Pull request closed without merging**
