### PR TITLE
Revert "Fix ToC in docs"

### PR DESCRIPTION
**Pull request by bhough**
Reverts styled-components/polished#59

### CODE REVIEW

**Comment by mxstbr** [comment]
No leave it, I'll fix it. One sec!

**Comment by mxstbr** [comment]
They look alright to me? Moved them to `/docs`... https://polished.js.org/docs/

**Comment by bhough** [comment]
Locally they are completely broken now and I see a docs folder with another docs folder inside of it in master, both with index.html files. Is this expected?

**Comment by mxstbr** [comment]
Yes, since `polished.js.org` (the homepage) will have a, well, homepage. That's why I moved the docs to `/docs` 😊 

Go to polished.js.org, nothing there (since there is not homepage yet, going to work on that), go to https://polished.js.org/docs, there's docs! 🎉

**Comment by bhough** [comment]
Ok, would be nice if we can link up the assets so the docs work locally. Right now they don't get styling or the js because the relative paths don't resolve. I

**Comment by mxstbr** [comment]
I use [`pushstate-server`](http://npm.im/pushstate-server) locally like this: `$ pushstate-server docs`, and it works for me. What do you use that it doesn't work?

**Comment by bhough** [comment]
I was just loading up index.html in the browser direction, i can move to using that.

**Comment by mxstbr** [comment]
Ooh, yeah that'll break since I had to resort to absolute links to the assets to make them work for the `docs/` suffix 😕 Maybe we should add an npm script for that?

**Comment by bhough** [comment]
I'll look into adding it as part of #56

**Pull request closed without merging**
