### PR TITLE
Add Timing Functions Mixin

### PR DESCRIPTION
**Pull request by bhough**
Addresses line item in #1

### CODE REVIEW

**Comment by bhough** [comment]
@mxstbr this is ready for review, but wanted your thoughts on how we want to return static values like this. My thought is having a function that returns it would keep it consistent with similar mixins that do work behind the scenes (like strip unit). That way the API is always the same. Thoughts?

**Comment by mxstbr** [comment]
I like it! What about adding a list of the functions we support to the docs?

**Comment by bhough** [comment]
good idea!

**Comment by bhough** [comment]
Added to docs and ready for review.

**Comment by mxstbr** [comment]
This LGTM, except for this:

screen shot 2016-11-18 at 10 52 40

Any way to fix that overflowing list? I'm sure there could be a better display for them.

**Comment by bhough** [comment]
So this turned out to be a bug of sorts with the theme instead of with how we are displaying it. Since we are going to need to customize the theme anyway, I brought the theme into the repo and fixed the bug on our copy that we will customize further later. 

Should be good to ship now once you approve.

**Pull request merged**
