### PR TITLE
[V2] Add readable text function for colors

### PR DESCRIPTION
**Pull request by LawJolla**
This PR adds a function that returns the most readable text color (white or black) based on another color.  I've found this function very helpful in my projects and should make a good addition to Polished. This function follows the W3C spec for luminosity.

I had a hard time naming the function.  If someone has a better name, by all means!

My tests returned passing with full code coverage.

NPM install deleted a lot in docs and made odd merge conflicts.  I assume that's something on the maintainers end/desirable, so I left that alone.

My editor is PhpStorm, so I had to add .idea to .gitignore. 

I greatly appreciate your help and allowing me to submit this first PR!

### CODE REVIEW

**Comment by LawJolla** [comment]
Hi @bhough ,

That's what I referred to by "NPM install deleted a lot in docs and made odd merge conflicts. I assume that's something on the maintainers end/desirable, so I left that alone."

`npm install` wrecked havoc with the docs folders and files.  I tried a clean install twice and both times it erased and modified /docs .

I didn't dig into it to figure out what was going on because I figured it was intentional / known.  The only files I'm adding are /src/colors/readableText.js and /src/colors/test/readableText.test.js and modified the .gitignore to add .idea.

**Comment by bhough** [comment]
Hey @LawJolla 

Sorry, missed that comment. I'm guessing you are running npm 4 and it is running the `prepublish` script when you are installing. 

However, that action should not be destructive beyond recreating `polished.js` and `index.html` if no other docs have changed.

Let's start troubleshooting by running `npm run prepublish` on it's own and see if you get any errors or a different result.

**Comment by LawJolla** [comment]
@bhough I've submitted an update above.  If this is too much of a mess and it'd be easier to kill this PR and submit a new one, please let me know.  Thanks!

**Comment by bhough** [comment]
@LawJolla it is probably best to start a fresh PR. Still a lot of artifacts in there from the build/failure fiasco. May be fast just to start a new branch and copy over the module/test files.

**Pull request closed without merging**
